fragment PortfolioParts on Portfolio {
  __typename
  title
  client
  category
  tags
  excerpt
  featured
  body
  image
  link
  seoTitle
  seoDescription
}

fragment BlogParts on Blog {
  __typename
  title
  excerpt
  category
  date
  readTime
  author
  featured
  image
  body
  seoTitle
  seoDescription
}
